/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lujun858_myplugindemo_JniUtils */

#ifndef _Included_com_example_lujun858_myplugindemo_JniUtils
#define _Included_com_example_lujun858_myplugindemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lujun858_myplugindemo_JniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lujun858_myplugindemo_JniUtils_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
